### ISSUE TITLE
[Feature Request] Jackett Search Indexer Support

### ISSUE THREAD

**Issue by zero77** [masterwok/simple-torrent-android#2]
Can you please add support for [Jackett](https://github.com/Jackett/Jackett) Search indexer, it can be implemented by using [Torznab](https://github.com/Sonarr/Sonarr/wiki/Implementing-a-Torznab-indexer).

Thanks
> Jackett works as a proxy server: it translates queries from apps (Sonarr, Radarr, SickRage, CouchPotato, Mylar, DuckieTV, etc) into tracker-site-specific http queries, parses the html response, then sends results back to the requesting software. This allows for getting recent uploads (like RSS) and performing searches. Jackett is a single repository of maintained indexer scraping & translation logic - removing the burden from other apps.

![hidden_mining](https://camo.githubusercontent.com/5b560454ad9fe411276cbeec42feb576d3cd06cb/68747470733a2f2f692e696d6775722e636f6d2f3064316e6c37672e706e67)

**Comment by masterwok** [comment]
Hi @zero77 this feature request is outside of the scope of simple-torrent-android. This project is just a client wrapper for frostwire-jlibtorrent and doesn't provided any search capabilities. Because of this, I'm going to close this feature request.

**Comment by zero77** [comment]
@masterwok 
Sorry, i wasn't sure which repo this best fits.

**Comment by masterwok** [comment]
All good, no worries.
