### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by DeevD** [masterwok/simple-torrent-android#3]
Add Speed and file size support for downloading torrent . And local Data base Support?

**Comment by masterwok** [comment]
Rates can be found on the TorrentSession:

- [TorrentSession.uploadRate](https://github.com/masterwok/simple-torrent-android/blob/master/simpletorrentandroid/src/main/java/com/masterwok/simpletorrentandroid/TorrentSession.kt#L447)
- [TorrentSession.downloadRate](https://github.com/masterwok/simple-torrent-android/blob/master/simpletorrentandroid/src/main/java/com/masterwok/simpletorrentandroid/TorrentSession.kt#L449)

The size of the file(s) being downloaded is represented on the [TorrentSessionStatus.bytesWanted](https://github.com/masterwok/simple-torrent-android/blob/master/simpletorrentandroid/src/main/java/com/masterwok/simpletorrentandroid/models/TorrentSessionStatus.kt#L23) property.

Is that what you're looking for?

**Comment by DeevD** [comment]
Thank bro i found it. Torrent Status and Torrent Info. When application is destroyed  torrentSession can be resume?.

**Comment by masterwok** [comment]
Awesome, no problem! 

When the application is stopped/destroyed the torrent session can be recreated and resumed. You will  want to have the TorrentSession managed within a foreground service so the download doesn't stop when the device goes to sleep.

**Comment by DeevD** [comment]
Thank you so much bro.

**Comment by masterwok** [comment]
Anytime, glad I could help!

**Comment by DeevD** [comment]
Can you provide example of local database with torrentSession bro. I mean when user is paused shut down application or device session can't be handle bro .

**Comment by masterwok** [comment]
Sorry, but that sample would be nearly an entire torrent client application. There's essentially going to be four main components you need to implement:

1. Managing TorrentSession instances within in a foreground service
2. Listening for TorrentSession events using a [TorrentSessionListener](https://github.com/masterwok/simple-torrent-android/blob/master/simpletorrentandroid/src/main/java/com/masterwok/simpletorrentandroid/contracts/TorrentSessionListener.kt)
3. Translating those events into models that can be persisted to a database (I used [Room](https://developer.android.com/topic/libraries/architecture/room))
4. Controlling sessions via user events

**Comment by DeevD** [comment]
:Okie bro no problem .  Thank for your suggestions.
