### ISSUE TITLE
Improvement: TorrentSession.kt

### ISSUE THREAD

**Issue by z1zong** [masterwok/simple-torrent-android#6]
First, It's a very great SDK and easy to use.
However, I notice some fatal errors in our app's firebase log related to 
line 303 to line 326:
```
private fun downloadUsingNetworkUri(
            downloadLocation: File
            , torrentUrl: URL
    ) {
        val connection = (torrentUrl.openConnection() as HttpURLConnection).apply {
            requestMethod = "GET"
            instanceFollowRedirects = true
        }

        connection.connect()

        if (connection.responseCode != 200) {
            Log.w(Tag, "Unexpected response code returned from server: ${connection.responseCode}")
        }

        val data = connection
                .inputStream
                .readBytes()

        sessionManager.download(
                TorrentInfo.bdecode(data)
                , downloadLocation
        )
    }
```
I'm guessing that when hostname is not available or somehow url not correct, this method will cause uncaught exceptions: net.ConnectException - Failed to connect to ${some url}. Is it better to put a tray-catch block to catch these exceptions?

**Comment by masterwok** [comment]
Thanks, I'm glad you are finding it useful. 

If I were you, I'd try/catch the portion of your application code that results in this function being executed and crashing down the line. This way your application can catch the exception and let the user know they provided an invalid path.

**Comment by z1zong** [comment]
Sorry, I did state the issue clearly.
this function is called by your SDK after I execute:
```
 AsyncTask.execute(new Runnable() {
                @Override
                public void run() {
                        torrentSession.start(context, url);
                }
            });
```
some users cannot connect to our host due to internet censorship, and this method (torrentSession.start(context, url)) cause a crash instead of throwing exceptions in callback listener.
I'm just suggesting that it will be better and an improvement that any errors related to url should be put in TorrentSessionListener.class
```
@Override
        public void onTorrentError(@NotNull TorrentHandle torrentHandle, @NotNull TorrentSessionStatus torrentSessionStatus) {
            
        }
```
Thanks for your reply. :)

**Comment by masterwok** [comment]
Thanks for the suggestion. Unfortunately, we can't use onTorrentError(...) callback as there is no TorrentHandle or TorrentSessionStatus instances available at this time. Even if we could, these callbacks are really just bubbling up events from the underlying jlibtorrent implementation so I wouldn't want to overload them. 

Would the following work for your use case?

```kotlin
 AsyncTask.execute(new Runnable() {
    @Override
    public void run() {
        try {
            torrentSession.start(context, url);
        catch(ex: Exception) {
            // Take action to notify the user something went wrong
        }
    }
});
```

**Comment by z1zong** [comment]
Thanks for your reply.
I will try this way, or find other ways.

**Comment by masterwok** [comment]
No problem, good luck!
